having_IP_Address: null
URL_Length: null
Shortining_Service: null
having_At_Symbol: null
double_slash_redirecting: null
Prefix_Suffix: null
having_Sub_Domain: null
SSLfinal_State: null
Domain_registeration_length: null
Favicon: null
port: null
HTTPS_token: null
Request_URL: null
URL_of_Anchor: null
Links_in_tags: null
SFH: null
Submitting_to_email: null
Abnormal_URL: null
Redirect: null
on_mouseover: null
RightClick: null
popUpWidnow: null
Iframe: null
age_of_domain: null
DNSRecord: null
web_traffic: null
Page_Rank: null
Google_Index: null
Links_pointing_to_page: null
Statistical_report: null
Result: null
